spring.application.name=inventory-management


# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT config
jwt.secret=${JWT_SECRET}
jwt.expiration=1800000
jwt.refresh-expiration=86400000



# Logging
logging.level.com.tricol.Tricol=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Oauth2 config
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/tricol
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/tricol/protocol/openid-connect/certs
#JWT issuer
jwt.issuer=tricol-local